## With the use of Google Cloud SDK (the gcloud command) to deploy applications on Google App Engine,
## it is no longer necessary to set the application name and version in the yaml application descriptor.
## In fact, it is actually prohibited! Thus, we need to comment out the following lines:

# application: sug-blog
# version: 1

## From now on, the project name should instead be specified either with the command
##              gcloud config set project sug-blog
## or by setting the --project flag on individual command executions, like:
##              gcloud app deploy --project sug-blog

runtime: python27
api_version: 1
threadsafe: yes

skip_files:
  # default files to ignore
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  # custom files to ignore
  - ^\.idea$

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: styles

- url: /assets
  static_dir: assets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
